{{- if .Values.serverDeployment.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: {{.Values.application.name}}
spec:
  maxReplicas: {{.Values.autoscaling.maxReplicas}}
  minReplicas: {{.Values.autoscaling.minReplicas}}

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.application.name}}

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage}}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ if .Values.autoscaling.targetMemoryUtilizationPercentage }} {{ .Values.autoscaling.targetMemoryUtilizationPercentage }} {{ else }} 60 {{ end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 240
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
{{- end }}
