{{- if .Values.workersDeployment.enabled }}
{{- range $worker := .Values.workers }}
{{- with $worker }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{$.Values.application.name}}-{{.name}}
  name: {{$.Values.application.name}}-{{.name}}
spec:
  replicas: {{ .minReplicas }}
  selector:
    matchLabels:
      app: {{$.Values.application.name}}-{{.name}}
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.add_error_key: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.message_key: payload
      creationTimestamp: null
      labels:
        app: {{$.Values.application.name}}-{{.name}}
        mode: worker
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "2"
      containers:
      - name: {{$.Values.application.name}}-{{.name}}
        env:
          - name: NODE_ENV
            value: "development"
          {{- with $index }}
          - name: {{.name}}
            value: {{.value}}
          {{- end }}
        image: "{{$.Values.image.repository}}:{{$.Values.image.tag}}"
        imagePullPolicy: {{$.Values.image.pullPolicy}}
        command: {{ if .command }} {{ toYaml .command | nindent 10 }} {{ else }} ["sh", "-c", "node worker.js && tail -f /dev/null"] {{ end }}
        ports:
        - containerPort: {{$.Values.service.targetPort}}
          protocol: TCP
        resources: 
          requests:
            cpu: {{.requests.cpu}}
            memory: {{.requests.memory}}
          limits:
            cpu: {{.limits.cpu}}
            memory: {{.limits.memory}}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: false
          capabilities:
            drop: [ 'NET_RAW', 'ALL' ] 
      dnsPolicy: ClusterFirst
      tolerations: 
      - key: "spotInstance" 
        operator: "Equal" 
        value: "true" 
        effect: "PreferNoSchedule" 
---
{{- end }}
{{- end }}
{{- end }}
